version: '3.9'

services:
  # Servidores Web Sub-rede A
  webserver_a:
    build:
      context: ./webserver_A
    networks:
      subnet_a:
        ipv4_address: 10.0.0.10
    ports:
      - "8080:80"

  # Servidores Web Sub-rede B
  webserver_b:
    build:
      context: ./webserver_B
    networks:
      subnet_b:
        ipv4_address: 20.0.0.10
    ports:
      - "8081:80"

  # Servidor DNS Sub-rede A
  dns_a:
    build:
      context: ./dns_A
    networks:
      subnet_a:
        ipv4_address: 10.0.0.11
    ports:
      - "5355:53/udp"  # Porta para DNS
    cap_add:
      - NET_ADMIN

  # Servidor DNS Sub-rede B
  dns_b:
    build:
      context: ./dns_B
    networks:
      subnet_b:
        ipv4_address: 20.0.0.11
    ports:
      - "5356:53/udp"
    cap_add:
      - NET_ADMIN

  # Firewall e DHCP
  firewall:
    build:
      context: ./firewall
    networks:
      subnet_a:
      subnet_b:
    cap_add:
      - NET_ADMIN
    ports:
      - "67:67/udp"  # Porta DHCP para IPv4
      - "68:68/udp"  # Porta DHCP para comunicação com clientes
    command: >
      sh -c "
        apt update && 
        apt install -y iptables isc-dhcp-server &&
        echo 'INTERFACESv4=\"eth0\"' > /etc/default/isc-dhcp-server &&
        sysctl -w net.ipv4.ip_forward=1 &&  # Habilita o roteamento
        iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE && 
        service isc-dhcp-server start && 
        tail -f /dev/null
      "
    volumes:
      - ./dhcpd.conf:/etc/dhcp/dhcpd.conf  # Arquivo de configuração DHCP
    environment:
      - DEBIAN_FRONTEND=noninteractive  # Evita prompts durante instalação

  
  # Hosts Sub-rede A
  host1_a:
    image: ubuntu:latest
    networks:
      subnet_a:
        ipv4_address: 10.0.0.100
    command: tail -f /dev/null  # Mantém o container ativo

  host2_a:
    image: ubuntu:latest
    networks:
      subnet_a:
        ipv4_address: 10.0.0.101
    command: tail -f /dev/null
  

  # Hosts Sub-rede B
  host1_b:
    image: ubuntu:latest
    networks:
      subnet_b:
        ipv4_address: 20.0.0.100
    command: tail -f /dev/null

  host2_b:
    image: ubuntu:latest
    networks:
      subnet_b:
        ipv4_address: 20.0.0.101
    command: tail -f /dev/null

networks:
  subnet_a:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
  subnet_b:
    driver: bridge
    ipam:
      config:
        - subnet: 20.0.0.0/24
